version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: BeSocial
      MONGO_INITDB_CONNECTION_URL: mongodb://admin:password@localhost:27017/BeSocial
volumes:
  mongodb_data: